### ISSUE TITLE
Title: Build Frontend for Custom Theme Generator Website

### ISSUE THREAD

**Issue by Kroszborg** [The-Red-Wood-Lab/Custom-Theme-Generator#3]
Description:

The task is to create the frontend for the Custom Theme Generator Website. The website allows users to select and customize colors, fonts, and styles for generating personalized themes for websites or applications.

Requirements:

    - Build using Next.js.
    - Provide a live preview that updates in real-time as users customize their theme.
    - The design should closely resemble the ShadCN UI Theme Generator on ZippyStarter.
    - Include options for:
        - Color selection (Primary, Secondary, Background, etc.).
        - Font selection.
        - Style customizations (Button styles, Navbar designs, etc.).
    - Implement smooth animations for theme transitions.
    - Responsive design for mobile, tablet, and desktop views.

Additional Features:

    - Download functionality: After creating their theme, users should be able to download a .json or .css file of their theme configuration.
    - Include a button to reset the theme to default settings.
    - (optional)Provide an option to copy the generated CSS or JSON configuration.

Please comment on this issue if you'd like to work on any of these tasks or if you have any questions or suggestions.

#hacktoberfest

**Comment by IngaleChinmay04** [comment]
I'm interested in taking on this task; I have experience with MERN but not with Next.js, so it will be a learning opportunity for me.

**Comment by eeshan15** [comment]
@IngaleChinmay04 It will be assigned to those who are a part of this organization please be a part of us than only it will be assigned. If you are interested do let me know I will invite you as a member for this organization. Thank You
